// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgrbyxkxlduvyxqfcwyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRncmJ5eGt4bGR1dnl4cWZjd3lsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0OTkzMjksImV4cCI6MjA2ODA3NTMyOX0.s7nFtrudd5lFJ0pCPDVymnY7eR4iNEPx4hV_v37tad8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});